/*
 * glo/mesh/shapes/sphere.cpp
 *
 * © Tim Clarke November 2025
 */

#include <glm/gtc/constants.hpp>

#include "sphere.h"

/*
 * Our vertices, indices, normals, and texture coordinates are all calculated in
 * createSphereData. We do not deindex the data, ensuring a smooth surface for
 * our mesh.
 */
SphereMesh::SphereMesh(GLuint segments, GLuint rings)
{
    const auto sphereData = createSphereData(segments, rings);

    setVertices(GL_TRIANGLES, sphereData.vertices);
    setIndices(sphereData.indices);
    setNormals(sphereData.normals);
    setTextureCoordinates(sphereData.texCoords);
}

/*
 * This method is based on code generated by DeekSeek. See the header file for
 * more information.
 *
 * numRings rings are created, each containing numSegments segments. The higher
 * these values are, the smoother our sphere will be, but will require more
 * vertices.
 */
SphereMesh::SphereData
SphereMesh::createSphereData(const GLuint numSegments, const GLuint numRings)
{
    SphereData data;

    for (GLuint ringIdx = 0; ringIdx <= numRings; ringIdx++)
    {
        // phi is used to determine this rings radius. Rings are largest in the
        // centre of the sphere, and taper down at each "end"
        const GLfloat phi = glm::pi<GLfloat>() * static_cast<GLfloat>(ringIdx) /
            static_cast<GLfloat>(numRings);
        const GLfloat ringRadius = RADIUS * std::sin(phi);

        // we only need to calculate y and v once per ring
        const GLfloat y = RADIUS * std::cos(phi);
        const GLfloat v = static_cast<GLfloat>(ringIdx)
            / static_cast<GLfloat>(numRings);

        for (GLuint segIdx = 0; segIdx <= numSegments; segIdx++)
        {
            // standard cos and sin trig to determine x and z coordinates
            const GLfloat theta = 2.0f * glm::pi<GLfloat>() *
                static_cast<GLfloat>(segIdx)
                / static_cast<GLfloat>(numSegments);
            const GLfloat x = ringRadius * std::cos(theta);
            const GLfloat z = ringRadius * std::sin(theta);

            // u is just an even distribution of points, based on the current
            // segment
            const GLfloat u = 1.0f - static_cast<GLfloat>(segIdx) /
                static_cast<GLfloat>(numSegments);

            const glm::vec3 position(x, y, z);
            data.vertices.push_back(position);

            // normals always radiate from the centre
            data.normals.push_back(glm::normalize(position));

            data.texCoords.push_back(glm::vec2(u, v));
        }
    }

    for (GLuint ringIdx = 0; ringIdx < numRings; ringIdx++)
    {
        for (GLuint segIdx = 0; segIdx < numSegments; segIdx++)
        {
            const GLuint current = ringIdx * (numSegments + 1) + segIdx;
            const GLuint next = current + numSegments + 1;

            data.indices.push_back(current);
            data.indices.push_back(current + 1);
            data.indices.push_back(next);

            data.indices.push_back(current + 1);
            data.indices.push_back(next + 1);
            data.indices.push_back(next);
        }
    }

    return data;
}
