/*
 * glo/mesh/shapes/star.h
 *
 * A star mesh. Includes normals only.  To apply a texture, DecalMesh should be
 * used.
 *
 * CITE: I asked DeepSeek (DeepSeek 2025) to generate code for several
 * variations of cogs, as I was considering project ideas and investigating the
 * possibility of a bronze clockwork mechanism. It had previously occurred to me
 * that the geometric shapes, with the test wraps I was using at the time,
 * reminded me of a child’s play room. I realised that I could create a star
 * mesh from similar code that DeekSeek had generated for one of the cogs. And
 * so though the generated code has been heavily modified to suit the new shape,
 * the original was generated by DeepSeek. The method generateEdge remains
 * mostly intact to what was generated, though winding did need to be fixed.
 * Overall, code was modified to cater for:
 *     • efficiency --- the code was cleaned up, duplication removed, and value
 *       calculations minimised. In particular, instead of four loops to
 *       generate the front and back faces, two of the loops were put into a
 *       method, and adapted to generate either face according to the z
 *       coordinate argument.
 *     • types --- the data types were changed to use OpenGL types (for example,
 *       from float to GLfloat).
 *     • winding --- winding had to be corrected.
 *     • adaption --- the relevant code was modified to create a star instead of
 *       a cog, and extracted to place into the StarMesh. Variable names were
 *       modified for consistency with the current codebase, and consts
 *       specified as appropriate.
 *
 * DeepSeek (2025). DeepSeek-V3.2-Exp. url: https://chat.deepseek.com
 *
 * For why triangle arrays are used instead of strips, see shapes/sphere.h
 *
 * © Tim Clarke November 2025
 */

#pragma once

#include <vector>

#include <glm/glm.hpp>

#include "../mesh_impl.h"

class StarMesh : public MeshImpl<glm::vec3>
{
    // === Radius of our star, giving a constructed size of 1.0 x 1.0 x 1.0
    static constexpr GLfloat RADIUS = 0.5f;

    // === How long the points should be.
    static constexpr GLfloat POINT_LENGTH = 0.2f;

    // === How many points to generate.
    static constexpr GLuint NUM_POINTS = 8;

  public:
    StarMesh();

  private:
    void generateFace(const GLfloat z, std::vector<glm::vec3> & vertices,
        std::vector<GLuint> & indices);
    void generateEdge(std::vector<glm::vec3> & vertices,
        std::vector<GLuint> & indices);
};
