/*
 * glo/scene/animators/orb.h
 *
 * Animates an orb to move to a random location within a fixed set of
 * coordinates above the ornaments. The orb's speed is determined by the
 * distance between the movement's start position and end position, and a random
 * time (between 3 and 8 seconds) that the orb has to complete the translation.
 *
 * CITE: I asked DeekSeek (DeepSeek 2025) to generate code for the Bezier
 * curves. I have experience in using Bezier curves with computer art programs,
 * but no prior knowledge of how they work. Therefore, apart from fitting the
 * code into the animator, the Bezier curve calculation is fully generated by
 * DeepSeek.
 *
 * DeepSeek (2025). DeepSeek-V3.2-Exp. url: https://chat.deepseek.com
 *
 * © Tim Clarke November 2025
 */

#pragma once

#include <GL/glew.h>
#include <glm/glm.hpp>

#include "animator.h"

class OrbAnimator : public Animator
{
  private:
    // The boundaries that contain the orb's target locations
    static constexpr GLfloat X_RADIUS = 2.0f;
    static constexpr GLfloat MIN_Y = 0.5f;
    static constexpr GLfloat MAX_Y = 3.0f;
    static constexpr GLfloat Z_RADIUS = X_RADIUS;

    // The min and max times the orb has to complete the translation
    static constexpr GLfloat MIN_TIME = 3.0f;
    static constexpr GLfloat MAX_TIME = 8.0f;

    // Values that create the "perfect" S-curve shape for Bezier curves.
    // CITE: DeekSeek
    static constexpr float CUBIC_COEFFICIENT = 3.0f;
    static constexpr float QUADRATIC_FACTOR = 2.0f;

  public:
    // Executes the animation transformation.
    void animate(const GLfloat deltaTime, SceneNode & node) override;

  private:
    // Returns a random number between min and max.
    GLfloat rand(const GLfloat min, const GLfloat max);

    GLfloat totalTime = 0.0f;
    GLfloat elapsedTime = 0.0f;

    glm::vec3 startPosition{0.0f};
    glm::vec3 targetPosition{0.0f};
    glm::vec3 bezierControlPosition{0.0f};
};
